### ISSUE TITLE
training error

### ISSUE THREAD

**Issue by kahnlzz** [reppy4620/Dialog#5]
Thank you for the great work.
I followed the usage guide in the github but some errors occurred. Any code not changed.
The following error occurred when copying pretrained model to './pretrained' folder  and executing 'python main.py'.
           "OSError: file ./pretrained/config.json not found"
'config.json' file was not found in your github.  When I copied the 'config.json' from original Bert, it was cleared.
After that, I got an error "OSError: file ./pretrained/pytorch_model.bin not found"
Please give me some tips to solve it.

Thanks in advance.
Seungkwon.

**Comment by reppy4620** [comment]
Sorry, I forgot to share about pretrained models.

Actually, for preparing "pytorch.bin", you have to convert original tf model to pytorch model using huggingface's convert script.
but it's too much bother to convert model.
Therefore I opened my "pretrained" folder to the public.
This is the [link](https://drive.google.com/open?id=1p_Pxmhn-sIrdtaVIM3-8YtbIiztSQE55).

Thank you for letting me know.

**Comment by kahnlzz** [comment]
Thank you for the kind response
